// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// IMPORTANT: Replace this file by running:
//   flutterfire configure
//
// This is a placeholder file. You MUST run the FlutterFire CLI to generate
// the actual configuration for your Firebase project.
//
// To do this:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. Select your Firebase project (or create a new one)
// 4. This file will be automatically replaced with your project's configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHwHTlPdrTxbfRXkfY6Ae4_2nunSWBZ-M',
    appId: '1:1027623118469:web:7a26485fb037711c4eebec',
    messagingSenderId: '1027623118469',
    projectId: 'tripit-456789',
    authDomain: 'tripit-456789.firebaseapp.com',
    storageBucket: 'tripit-456789.firebasestorage.app',
  );

  // PLACEHOLDER VALUES - Replace by running: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeucYsIqJvNgrx_vryo5gbmpH5Uyk-DrY',
    appId: '1:1027623118469:android:e34b7c441d49e3454eebec',
    messagingSenderId: '1027623118469',
    projectId: 'tripit-456789',
    storageBucket: 'tripit-456789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBuQP22kM4ZWZJkWrEBjtuHrmMFwfOqM',
    appId: '1:1027623118469:ios:a066f66182ee525f4eebec',
    messagingSenderId: '1027623118469',
    projectId: 'tripit-456789',
    storageBucket: 'tripit-456789.firebasestorage.app',
    iosBundleId: 'com.example.tripit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBuQP22kM4ZWZJkWrEBjtuHrmMFwfOqM',
    appId: '1:1027623118469:ios:a066f66182ee525f4eebec',
    messagingSenderId: '1027623118469',
    projectId: 'tripit-456789',
    storageBucket: 'tripit-456789.firebasestorage.app',
    iosBundleId: 'com.example.tripit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHwHTlPdrTxbfRXkfY6Ae4_2nunSWBZ-M',
    appId: '1:1027623118469:web:53f50af0c32264344eebec',
    messagingSenderId: '1027623118469',
    projectId: 'tripit-456789',
    authDomain: 'tripit-456789.firebaseapp.com',
    storageBucket: 'tripit-456789.firebasestorage.app',
  );

}